const express = require("express");
const app = express();
const cors = require("cors");
const PORT = 8000;

app.use(cors());
const lifePaths = {
  1: {
    number: " 1",
    info: "People born with a Life Path number 1 are on a lifelong mission to exert their independence and step into their personal power. They carry a natural air of authority as a leader who likes to be the first to try something new. A strong desire for manifestation keeps them moving and improving.People with a Numerology Life Path 1 are born to act quickly and have no problem changing course and starting down a new path. A secret fear of failure makes them ultra-driven in every endeavor they pursue and will often make them victorious. As soon as one finish line is reached, they are already running toward another.A feeling of isolation may follow people with this Life Path, but it's also what helps them make progress. Cooperating with other people in romantic relationships or teamwork settings can be difficult for number 1 people, who prefer to go their own way. They don't identify much with others' pursuits and only feel free when they are unattached. A thriving love life is not usually one of their goals.The Life Path 1 in Numerology likes to move quickly and this can come across as impatience or short-sightedness to others. However, it's this trait that makes people with a 1 Life Path number the early birds who are the first to take advantage new opportunities and the first to reap the rewards. While other people are weighing their options and making long-term plans, those with a Life Path 1 are already in motion, confident they can make things up as they go along.",
  },
  2: {
    number: "2",
    info: "People that were born with a 2 Life Path are blessed with beautiful hearts that they use to bring beautiful relationships into their lives.From romantic and business partnerships to family and friendships, these bonds are the most valuable thing in life to a person with a Life Path 2. They thrive in being part of a team and will do everything in their power to make it a happy, easy, and successful union. They are incredibly giving and do well at creating long-lasting connections with others.Every action and decision of a person with a Life Path number 2 is geared at creating a harmonious existence. From the professional path they choose to who they surround themselves with to their spiritual pursuits, it's all driven by a desire for peace. To this end, however, 2 people can be so passive that they miss out on their full potential. Whether this means staying silent about things that upset them or not asking for a raise or promotion to avoid rocking the boat, people with this Life Path can suffer from never putting their needs first.The subconscious mind is extremely powerful for a person born with a 2 Life Path. They may often just 'know' things about people they meet or be able to sense the undercurrent of a situation before it reveals itself. This level of intuition allows people with a number Life Path number 2 to get in front of problems and address them before they start to throw things off balance. In relationships, the ability to sense what another person is thinking or feeling gives these people an understanding, compassionate quality that makes others feel nurtured.",
  },
  3: {
    number: "3",
    info: "Charming, romantic, and full of creative energy, people who were born with a 3 Life Path number know how to embrace life! They tend to see the world through rose-colored lenses where everything looks like an opportunity and the chances for expression and enjoyment are endless. They have a tendency to be skilled communicators and have a knack for coming up with and sharing brilliant ideas. The Life Path 3 makes an excellent journalist, blogger, social media influencer, or author.People with a Life Path number 3 enjoy an active social life where they can interact with others often. From the moment of birth, their light is warm and exciting and draws many friends and admirers. They tend to be extroverted and embrace any opportunity to show off their original thoughts and stand-out personality. They have a way with words and can charm their way into anyone's heart.But while Life Path 3 people are great at attracting others, forming real, deep bonds is the difficult part. They want to keep things fun and new but feel they have to give that up if they make themselves vulnerable to intimacy. Those with this Life Path live in the moment, so the idea of committing to anything long-term can be a daunting one.A person with this Life Path number is very fun to be around, but could also benefit from embracing a deeper, more spiritual side of life. While those with a 3 Life Path truly enjoy who they are and what they do, there's a more meaningful level of experience and emotion that people with this Life Path may never even know exists. It's an untapped well of ideas to explore and engage with if they will muster up the courage to go to a deeper, more spiritual level.Though people born with a Life Path number 3 will be dealt both joy and hardship just like the rest of us, their unique way of thinking and dedication to happiness allow them to always see the silver lining. The power of positivity goes a long way for people with this Life Path. ",
  },
  4: {
    number: "4",
    info: "Dedicated, patient, down to earth, and hard-working, people with a 4 Life Path number are a great source of stability in our world. They aren't interested in rocking the boat because they know that constant, steady effort is the surest path to their goals. Life Path 4 people are consistent in their methods and their moods and they keep themselves composed. They experience a range of emotions just like everyone else, but their practical way of processing their feelings keeps them from going to extremes.With a wide range of knowledge, Life Path number 4 people are natural teachers. They are confident in what they know and speak with such clarity and authority that others accept what they say. They need to remember, though, that they are also students and that there is always, always more to learn. Life Path 4 people tend to make firm decisions about what is 'right' and close the door on anything new or different. Stuck with outdated methods and old information, these people may come up short of their true potential.In relationships, people with a 4 Life Path are honest, loyal, and committed, and they need the same from a partner. Trust and fidelity are vital to them and its important they find someone who shares their religious perspectives and values. 4 people will not waste their time with someone they're not compatible with, but when they find that special someone, they work hard to make the relationship successful and are in it for the long haul. Though a relationship with a Life Path number 4 person won't be the most exciting one, it is sure to be stable and prosperous.",
  },
  5: {
    number: "5",
    info: "People with a 5 Life Path number are on a lifelong adventure. They are ready for anything and want to soak up every experience this world has to offer. Life Path number 5 people tend to learn by living and don't allow themselves to get stuck in any situation that has outworn its interest. The moment things start to get humdrum, a person with this Life Path will move on to something more fascinating.Routine is unbearable to people with a Life Path 5, so typical 9-5 jobs are not appealing to them. Though they will change their career path many times throughout life, positions that allow them the freedom to make their own decisions will be the most satisfying. And whether on the job or off, making time for travel will be key to feeling fulfilled for those with this Life Path.Meeting new people is no problem for a person with this Life Path number -- they are very social creatures by nature and enjoy engaging with others. What is more difficult for these people is maintaining friendships and romantic relationships beyond the initial stages. They have a tendency to lose interest and bow out before there's a chance to make a deeper connection. When they are in a relationship, people with a Life Path number 5 make exciting partners who want to show and share everything with their companion. However, their fickle and flighty nature makes it tough to ever really get close.If there's one thing a Life Path 5 person's life will never be, it's boring. To them, life is about experimenting and engaging and learning and enjoying and they can't wait to take it all in each and every day. Anyone with the 5 Life Path doesn't always know exactly where they're going, but they're guaranteed an epic journey.",
  },
  6: {
    number: "6",
    info: "People born with a Life Path 6 embrace their emotions and lead with their heart. They give off a warm and inviting energy that others want to be around. They enjoy many rich relationships throughout their life, both romantic and friendly. Whether these Life Path people encounter someone who is just like them or someone who is entirely different, they will treat them the same: with kindness, respect, and support. Some Life Path numbers only see black and white, but the Life Path number 6 can see and accept the infinite shades of grey between.With a natural ability to connect with others and offer aid and advice, 6 people do well as professional counselors, mentors, and teachers. These people are also natural humanitarians, eager to speak up, raise funds, and offer emotional support and protection for those that need it. This Life Path truly embraces the meaning of 'A candle loses nothing by lighting another candle.' They have an infinite well of love to give, and they know the world could use it.The love life of a person born with a 6 Life Path number is deep and romantic. They are refreshing to partners who may be used to lovers who don't relate as well to their feelings. Though not every relationship can be a lifelong one, 6 Life Path people are devoted to love and harmony and committed to making things last. What these people need to remember, however, is that they are also individuals. It may be noble to sacrifice oneself to love, but it's not healthy. People with a Life Path number 6 must remember to direct the same attention they give others onto themselves. Only then will they feel truly, universally balanced.",
  },
  7: {
    number: "7",
    info: "People born with a Life Path 7 are eternal students of the universe. They are introspective individuals with an unquenchable thirst for knowledge and they enjoy looking into the inner workings of things. Someone with this Life Path is a true thinker who lets their mind lead the way. Pretty much from the moment of birth, they are able to skillfully combine the exacting side of their brain with their divine intuitive side to learn about, process, and make sense of life itself.The 7 Life Path in Numerology is smart in a knowledgeable way, yet wise in a spiritual way. People with this Life Path number enjoy gaining book smarts, but they are also more connected to their higher self than most and have great access to this inner wisdom. While they are spiritual creatures, though, Life Path 7 people don't tend to be the religious type. Strict doctrines that don't make room for new information are a turn-off to these inquisitive folk.Similar to The Hermit in a Tarot deck, people born with a Life Path number 7 often go it alone. They like the freedom of not having to explain themselves and enjoy the control and possibility of solitude. Their social circle tends to be a small one made up of people with like-minded interests. They may come across to the world as a bit awkward in groups or when meeting new people. Romantically, people with this Life Path may find it hard to connect on an emotional level with others. They love the part of getting to know someone, asking questions and exchanging answers, but often lack the interest or ability to build a heartfelt bond.Professions that require research and problem-solving skills are a perfect fit for those with a Life Path 7. If given a quiet space to think and work, they'll dive deeper than anyone into a problem and come out with the most valuable and viable solution. Their analytical powers are off the charts and these skills make them an asset to any project or team.",
  },
  8: {
    number: "8",
    info: "The Life Path number 8 personality is one of hard work and hard lessons. People born with this Life Path number get their worth from accomplishing great things -- the bigger the goal, the more satisfying it feels when they achieve it. Money and material goods are important to them because they are rewards and reminders of all the effort put in. People with this Life Path direct all their energy into creating a life of success and abundance.Dealing with people in positions of authority is often tough for people born with an 8 Life Path number. Because they are leaders themselves and are supremely confident in their abilities, they don't take kindly to being told what to do -- especially if it goes against what they would choose to do. Life Path 8 people, too, can also come across as authoritative and must learn that all relationships are about harmony.With all the work these Life path people put into reaching their goals and feeling accomplished, they would be wise to pay attention to their health. Stress is the all-too-familiar enemy of those born with the 8 Life Path number and, if allowed, it will slow down or deter these people on their path to reaching their goals. Making time for meditation, friendship, and enjoyable pursuits helps to bring things back into balance. Health is wealth, so maintaining a healthy lifestyle should be a top priority.When it comes to relationships, people with an 8 Life Path will put in the same work and dedication that they put into everything else. They do well in long-term situations, but these relationships may look more like business arrangements than passionate love affairs. Life Path number 8 people see themselves as providers and willingly take on the role of supporting a partner or family. They know they are self-sufficient, but when they see that they are prosperous enough to also provide for loved ones, to them, that's proof of success.",
  },
  9: {
    number: "9",
    info: "There's a special kind of magic that follows people born with a 9 Life Path number. They embody the wisdom of a sage, but not by chance -- they have fought their way through many challenges to reach this point and have gained immeasurable strength and awareness along the way. Life Path number 9 people will often find themselves in a position of providing support and advice and this feels natural to them. The knowledge they have gained can be incredibly valuable to others on their own journeys.A person who is born with a Life Path 9 tends to be spiritual and connects deeply with religion. Whether it stems from a need for strength during times of struggle or a natural desire to relate to something greater than themselves, Life Path number 9 people often seek courage and meaning from a higher source. Intuitions and gut reactions may even outweigh logic. This connection to the divine gives these people a safety net of confidence as they continue to make their way through life's good times and bad.People with a Life Path 9 may feel a great devotion to their fellow man. They are humanitarians by nature and use their big hearts to support those who have been made to feel inequal or unworthy. But because 9 Life Path people have become so accustomed to enduring their own challenges, others may not notice when they are in need and, unfortunately, they have a very difficult time asking for help. People with this Life Path number must realize that assistance is part of a cycle of give and take, and with as much support as they give, it's their karmic responsibility to receive support in return",
  },
  11: {
    number: "11",
    info: "People with an 11 Life Path are unbelievably intuitive and may even exhibit psychic abilities. Their purpose is to use these gifts to better humanity, but it could take a long time before people born with this Life Path number to truly understand the power they possess.Having any Master Number as a Life Path number can come with its own complications. In the case of Life Path number 11, confidence and worry can plague those born with it. This can mean that people with an 11 Life Path struggle with trusting and sharpening their unique skills. But, if they can overcome this, they will be able to channel their intuition and maximize their emotional awareness of the world around them.Those with a Life Path 11 can become incredibly spiritual, especially since these energies are coursing their veins every single day. They usually believe in a higher power -- but that has more to do with accessing higher truths about life than following the dogma of organized religion.Someone with a Life Path 11 are beautiful souls, which easily attracts others to them. The 11 Life Path does well in relationships because they are usually very attuned to their partner's emotions, anticipating what their significant other needs before they do.In order to fulfill their Master Number potential, they must not turn their backs on their special abilities or they will face inner turmoil. Having a Life Path number 11 people must lean into their life purpose by harnessing their psychic skills. By doing so, they will reach incredible spiritual enlightenment.",
  },
  22: {
    number: "22",
    info: "The 22 Life Path is called the 'Master Builder' because it has a very special power to turn nebulous dreams into concrete realities. These people are spiritually connected and feel both a responsibility and a burden to use their cosmic gift to better the future of our world. And though it may take years to master to their life purpose, what a 22 Life Path can achieve is exceptional.One of the things that set a Life Path 22 apart from others is their extreme dedication. They aren't afraid of putting in the hard work -- but this isn't about climbing the corporate ladder. They feel an allegiance to others, working hard to be of service to others and improving humankind in some way. This can lead to a fear of failure, but they can turn this around and use it as motivation to keep pushing forward.Those with a Life Path number 22 are not only able to lead themselves, but others as well. They don't rely on their emotions, but this can come at a cost as they sometimes come across as 'all work and no play.' However, they understand the value of cooperation and know that those who go far go together.Fulfillment for someone with a Master Number 22 comes in the form of seeing how their hard work has come to fruition. Their ambition is unmatched, and nobody sets the bar higher than they do, so they need to know they've done a good job. By embracing their abilities and knowledge, they will be able to do just that.",
  },
  33: {
    number: "33",
    info: "Birthdays that add up to a Life Path 33 are very rare -- it takes a specific and uncommon combination of numbers in a person's birth date to add up to this number. Anyone born with this Life Path number are known as 'Master Teachers.' They are healers and great spiritual leaders devoted to showing others how to connect to their own heart and consciousness.One of the most common traits for a Life Path number 33 is altruism. Their selfless spirit makes them excellent partners, as they are able to listen with intention and offer unparalleled emotional support.Being born with a Life Path 33 can feel like both a blessing and a curse. Individuals with this Life Path can experience a level of spiritual understanding and empathy that most others couldn't begin to comprehend. However, in order for them to achieve this, they must face a series of obstacles throughout their lives that will test them. One of their greatest lessons is to heal themselves before they can exercise their power of healing others.While it can take almost their entire lives to master being a Life Path number 33, all the work will be worth the self-actualization that people with this Life Path number are able to achieve.",
  },
};

app.get("/", (req, res) => {
  res.sendFile(__dirname + "/index.html");
});

// /api:lifeNum we are creating our own link to the api that is user side that is used when making a request. This can be whatever we want to call query
//params is used in express for req the parameter in the link
app.get("/api/:lifeNum", (req, res) => {
  // const lifeNums =
  const paths = req.params.lifeNum; //assigning a varible for req
  res.json(lifePaths[paths].info); //responding with the data as with json- this is pulling from the object that was created
  //if we were checking for a name that had spaces dot notation would not work would have to use brackets

  //this is checking for whatever is passed in is a property of lifePaths, if it is inside of object respond with result
  //   console.log(lifePaths[paths].info);

  if (lifePaths[paths]) {
    res.json(lifePaths[paths].info);
  } else {
    console.log("error");
    // res.json(lifePaths[unknown]);
  }
});
//process.env.PORT allows heroku the option to use their own selected port
app.listen(process.env.PORT || PORT, function () {
  console.log(`The Server Is Running On Port ${PORT}!`);
});
console.log("is this working");
//for heroku
// app.listen(proccess.env.PORT || PORT, function () {
//   console.log(`The Server Is Running On Port ${PORT}!`);
// });
